### ISSUE TITLE
Remove failure entirely

### ISSUE THREAD

**Issue by nagisa** [harryfei/which-rs#20]
As of 1 hour ago, failure is now broken entirely because it was relying on implementation details of `quote` and quote decided to not tolerate it in https://github.com/dtolnay/quote/commit/41543890aa76f4f8046fffac536b9445275aab26.

Please remove use of failure entirely.

**Comment by harryfei** [comment]
The failure integration is optional. You can disable it by adding those lines in your `Cargo.toml`
```toml
[dependencies.which]
version = "3.0.1"
default-features = false 
```
Does it work in your case?
